
package io.objectbox;

import io.objectbox.ModelBuilder.EntityBuilder;
import io.objectbox.model.PropertyFlags;
import io.objectbox.model.PropertyType;

// THIS CODE IS GENERATED BY ObjectBox, DO NOT EDIT.

/**
 * Starting point for working with your ObjectBox. All boxes are set up for your objects here.
 * <p>
 * First steps (Android): get a builder using {@link #builder()}, call {@link BoxStoreBuilder#androidContext(Object)},
 * and {@link BoxStoreBuilder#build()} to get a {@link BoxStore} to work with.
 */
public class MyObjectBox {

    public static BoxStoreBuilder builder() {
        BoxStoreBuilder builder = new BoxStoreBuilder(getModel());
        builder.entity(RequestHistory_.__INSTANCE);
        return builder;
    }

    private static byte[] getModel() {
        ModelBuilder modelBuilder = new ModelBuilder();
        modelBuilder.lastEntityId(1, 2193873073256546690L);
        modelBuilder.lastIndexId(0, 0L);
        modelBuilder.lastRelationId(0, 0L);

        buildEntityRequestHistory(modelBuilder);

        return modelBuilder.build();
    }

    private static void buildEntityRequestHistory(ModelBuilder modelBuilder) {
        EntityBuilder entityBuilder = modelBuilder.entity("RequestHistory");
        entityBuilder.id(1, 2193873073256546690L).lastPropertyId(7, 4416053523633551718L);

        entityBuilder.property("id", PropertyType.Long).id(1, 1436145746691920833L)
                .flags(PropertyFlags.ID);
        entityBuilder.property("method", PropertyType.String).id(2, 4874359363142308330L);
        entityBuilder.property("url", PropertyType.String).id(3, 5099522648896388409L);
        entityBuilder.property("headers", PropertyType.String).id(4, 1105875428006868395L);
        entityBuilder.property("queryMaps", PropertyType.String).id(5, 4548229289444669365L);
        entityBuilder.property("bodyJson", PropertyType.String).id(6, 1431269715420152488L);
        entityBuilder.property("date", PropertyType.Date).id(7, 4416053523633551718L);


        entityBuilder.entityDone();
    }


}
